---
host_interfaces:
  - role: default
    cidr: 192.168.122.0/24
    bridge: virbr0
    name: ens3
  - role: host-only
    cidr: 192.168.133.0/24
    bridge: virbr1
    name: ens4
  - role: external-nat
    cidr: 192.168.150.0/24
    bridge: virbr3
    name: ens5
