---
clean: False

###############
# Kolla nodes #
###############

kolla_hypervisor: localhost
kolla_vm_names:
  - controller-1
  - compute-1

#######################
# ODL Master settings #
#######################
odl_latest_enabled: true
odl_latest_url: https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/integration/netvirt/karaf/0.8.0-SNAPSHOT/karaf-0.8.0-20171008.162947-1069.zip

############################
# Docker registry defaults #
############################
docker_registry_ip: 172.26.0.1
docker_registry_port: 5000

#################
# Build default #
#################
tmp_dir: /tmp

build_overrides:
  - section: DEFAULT
    option: template_override
    value: "{{ tmp_dir }}/kolla/contrib/template-override/opendaylight-template-overrides.j2"
  - section: DEFAULT
    option: push
    value: true
  - section: DEFAULT
    option: registry
    value: "{{ docker_registry_ip }}:{{ docker_registry_port }}"
  - section: DEFAULT
    option: install_type
    value: source
  - section: opendaylight
    option: type
    value: url
  - section: opendaylight
    option: location
    value: https://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/distribution-karaf/0.6.1-Carbon/distribution-karaf-0.6.1-Carbon.tar.gz
  - section: profiles
    option: odl
    value: opendaylight,thrift-quagga,chrony,cron,kolla-toolbox,fluentd,glance,haproxy,heat,horizon,keepalived,keystone,mariadb,memcached,neutron,nova,openvswitch,rabbitmq,skydive,tacker,elasticsearch,barbican,mistral,redis,aodh,gnocchi,ceilometer
