---

######################
# Features to enable #
######################

enable_opendaylight: "yes"
odl_latest_enabled: "yes"
enable_skydive: "yes"
enable_tacker: "yes"


###############
# Kolla nodes #
###############

kolla_hypervisor: localhost
kolla_vm_snapshot_name: post-install
kolla_vm_names:
  - controller-1
  - compute-1

#############################
# Kolla passwords overrides #
#############################
password_overrides:
  keystone_admin_password: admin
  opendaylight_password: admin

###############################
# Kolla globals.yml overrides #
###############################
globals_override:
  network_interface: "{{ kolla_node_internal_intf }}"
  neutron_external_interface: "{{ kolla_node_external_intf }}"
  kolla_install_type: "source"
  docker_registry: "{{ docker_registry_ip }}:{{ docker_registry_port }}"
  docker_namespace: "kolla"
  kolla_internal_vip_address: 192.168.133.254
  enable_neutron_sfc: "yes"
# Opendaylight settings
  enable_opendaylight: "{{ enable_opendaylight | bool }}"
  neutron_plugin_agent: "{{ 'opendaylight' if enable_opendaylight | bool else 'openvswitch' }}"
# Skydive settings
  enable_skydive: "{{ enable_skydive | bool }}"
  enable_elasticsearch: "{{ enable_skydive | bool }}"
# Tacker settings
  enable_tacker: "{{ enable_tacker | bool }}"
  enable_barbican: "{{ enable_tacker | bool }}"
  enable_mistral: "{{ enable_tacker | bool }}"
  enable_redis: "{{ enable_tacker | bool }}"
  enable_aodh: "{{ enable_tacker | bool }}"
  enable_ceilometer: "{{ enable_tacker | bool }}"
  enable_gnocchi: "{{ enable_tacker | bool }}"

#######################
# Inventory overrides #
#######################
inventory_override:
  control01: controller-1
  control02: ''
  control03: ''
  network01: controller-1
  network02: ''
  monitoring01: controller-1
  storage01: compute-1
  compute01: compute-1

############################
# Docker registry defaults #
############################
docker_registry_ip: 172.26.0.1
docker_registry_port: 5000

#####################
# Kolla host defaults
#####################
tmp_dir: "/tmp"
kolla_node_internal_intf: ens4
kolla_node_external_intf: ens5
kolla_node_home_dir: "{{ ansible_env.HOME }}"

################
# Quagga Role  #
################
quagga_files:
  - name: defaults
    files: [main.yml]
  - name: handlers
    files: [main.yml]
  - name: tasks
    files: [main.yml, deploy.yml, config.yml, pull.yml, precheck.yml]
  - name: templates
    files: [quagga.json.j2]

###############
# BUG FIXES ###
###############

override_start_ovs: True


