---
project_name: "quagga"

quagga_services:
  quagga:
    container_name: "quagga"
    image: "{{ opnfv_quagga_image_full }}"
    enabled: True
    privileged: True
    group: "opendaylight"
    host_in_groups: "{{ True if orchestration_engine == 'KUBERNETES' else inventory_hostname in groups['opendaylight'] }}"
    volumes:
      - "{{ node_config_directory }}/quagga/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"

####################
# Docker
####################

opnfv_quagga_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-opnfv-quagga"
opnfv_quagga_tag: "{{ openstack_release }}"
opnfv_quagga_image_full: "{{ opnfv_quagga_image }}:{{ opnfv_quagga_tag }}"
