---
project_name: "quagga"

quagga_services:
  quagga:
    container_name: "quagga"
    image: "{{ thrift_quagga_image_full }}"
    enabled: True
    privileged: True
    group: "opendaylight"
    host_in_groups: "{{ inventory_hostname in groups['opendaylight'] }}"
    volumes:
      - "{{ node_config_directory }}/quagga/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"

####################
# Docker
####################

thrift_quagga_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-thrift-quagga"
thrift_quagga_tag: "{{ openstack_release }}"
thrift_quagga_image_full: "{{ thrift_quagga_image }}:{{ thrift_quagga_tag }}"
