---

#- name: debug all variables
#  debug:
#    var: hostvars
- name: Stop local docker registry
  docker_container:
    name: "{{ docker_registry_name }}"
    image: registry:2
    state: absent
  ignore_errors: True

- name: Destroy VMs
  become: True
  shell: "virsh destroy {{ item.name }}"
  with_items: "{{ kolla_nodes }}"
  ignore_errors: yes

- name: Undefine VMs
  become: True
  shell: "virsh undefine {{ item.name }}"
  with_items: "{{ kolla_nodes }}"
  ignore_errors: yes

- name: Delete qcow2 images
  become: True
  file:
    path: "{{ libvirt_dir }}/{{ item.name }}.qcow2"
    state: absent
  with_items: "{{ kolla_nodes }}"
  ignore_errors: yes
